### ISSUE TITLE
Loggable Mixin

### ISSUE THREAD

**Issue by kesslerdev** [kesslerdev/quarkit#11]
implement https://github.com/pimterry/loglevel  as a loggable mixin  & mix with gameObject & remove all console.log

**Comment by Skowt** [comment]
Looking at doing this.

**Comment by Skowt** [comment]
Not sure if it's just me being silly but while trying to run your code locally I keep getting:
`Error: Couldn't find preset "es2015" relative to directory "/Users/skowt/quarkit/packages/quarkit-mixin"`

Is there a `babelrc` file that isn't in the repo or a dependency somewhere that was missed out?

**Comment by kesslerdev** [comment]
this project uses lerna & yarn workspaces, you can look in package.json for differents scripts.

this issue need te be done in gameobject mixin (in quarkit-core package), for future a basic implement of a mixin https://github.com/kesslerdev/quarkit/pull/18
